# action.yml
name: 'Detects performance or front-end code quality issues'
description: 'Analyzes a webpage and detects performance or front-end code quality issues'
branding:
  icon: 'check-circle'  
  color: 'gray-dark'
inputs:
  url:
    description: 'URL to analyse'
    required: true
  score:
    description: 'The desired performance and front-end score'
    required: true
  host:
    description: 'The API host url, defaults to https://yellowlab.tools/api/runs'
    required: false
outputs:
  score:
    description: 'The performanc and front-end global score'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.score }}
    - ${{ inputs.host }}
